"""Test twin for parts/world/combat_clock.py -- the shared round timer, exercised directly.

The clock is job-blind: it counts down whatever cooldowns/statuses a session carries and
regenerates the job's Power Cells. These pin that behavior without any ability or combat in
the loop. Engineer's twin proves its abilities ride the same clock; combat's twin proves a
basic strike advances it.
"""

from parts.world.combat_clock import advance
from parts.world.jobs import bind_calling
from parts.world.session import Session


def test_cooldowns_count_down_and_the_expired_drop_off():
    s = Session(player_id="matrym")
    s.cooldowns["field_repair"] = 2
    advance(s)
    assert s.cooldowns["field_repair"] == 1  # one tick down
    advance(s)
    assert "field_repair" not in s.cooldowns  # reached zero, dropped off


def test_statuses_count_down_independently():
    s = Session(player_id="matrym")
    s.statuses["barrier"] = 3
    s.statuses["analyzed"] = 1
    advance(s)
    assert s.statuses["barrier"] == 2
    assert "analyzed" not in s.statuses  # the shorter status expired first


def test_an_empty_clock_is_a_safe_no_op():
    s = Session(player_id="matrym")  # no cooldowns, no statuses, no power
    advance(s)  # must not raise
    assert s.cooldowns == {}
    assert s.statuses == {}


def test_power_cells_regenerate_toward_the_maximum():
    s = Session(player_id="matrym")
    bind_calling(s, "engineer")  # the Engineer carries a Power resource with a per-tick regen
    power = s.resources["power"]
    s.resources["power"] = power.damage(power.maximum)  # drain it to zero
    advance(s)
    assert s.resources["power"].current > 0  # regenerated by the job's per-tick rate


def test_a_job_without_power_regen_is_untouched():
    s = Session(player_id="matrym")
    bind_calling(s, "vanguard")  # no Power resource
    advance(s)  # must not raise on a missing power resource
    assert "power" not in s.resources
