"""initial schema: characters and accounts

Revision ID: f70a020a8288
Revises:
Create Date: 2026-07-10 17:21:29.375788

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f70a020a8288"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("auth_salt", sa.String(), nullable=False),
        sa.Column("auth_hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "characters",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("job", sa.String(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("rank", sa.String(), nullable=False),
        sa.Column("account", sa.String(), nullable=False),
        sa.Column("auth_salt", sa.String(), nullable=True),
        sa.Column("auth_hash", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("characters")
    op.drop_table("accounts")
    # ### end Alembic commands ###
