"""Record the README demo GIF from REAL aethryn gameplay - reproducible, not hand-captured.

The demo is not a mystery artifact: it is generated by driving the actual engine tick through the
Relighting arc and pacing the transcript into an asciinema v2 cast. Combat is deterministic, so the
same script yields the same session every run.

Usage:
    FORGE_SEED=aethryn python scripts/record_demo.py [cast_path]   # writes the .cast
    agg --theme dracula --font-size 15 --speed 1.2 --fps-cap 24 \\
        --last-frame-duration 4 demo.cast docs/demo.gif           # renders the GIF

`agg` (the asciinema gif generator) is the only extra tool needed, and only to render; it is not a
runtime or CI dependency. `make demo-gif` runs both steps.
"""

from __future__ import annotations

import json
import os
import sys

os.environ.setdefault("FORGE_SEED", "aethryn")

import forge  # noqa: E402  (import after FORGE_SEED so the world loads the flagship)
from parts.session import Session  # noqa: E402
from parts.world import START_ROOM  # noqa: E402

WIDTH, HEIGHT = 94, 32
AMBER_PROMPT = "\x1b[1;38;5;214m> \x1b[0m"

# The arc, played from real actions: relight fires on the pickup, delve on entering the cellar,
# and the fight ends the story. (label, seconds to hold the reply on screen)
NARRATIVE: list[tuple[str, float]] = [
    ("look", 1.9),
    ("job vanguard", 1.5),
    ("quest accept", 1.9),
    ("get ember", 2.1),
    ("north", 2.0),
    ("quest reforge", 2.0),
    ("down", 2.1),
    ("down", 1.9),
]


def build_cast(session: Session) -> list[list[object]]:
    """Drive the game and return asciinema v2 output events with paced, synthetic timestamps."""
    events: list[list[object]] = []
    clock = 0.0

    def emit(data: str, hold: float) -> None:
        nonlocal clock
        events.append([round(clock, 3), "o", data.replace("\n", "\r\n")])
        clock += hold

    def prompt_and_type(cmd: str) -> None:
        emit(AMBER_PROMPT, 0.15)
        for char in cmd:
            emit(char, 0.04)
        emit("\r\n", 0.3)

    def play(cmd: str) -> str:
        return (forge.handle_command(session, cmd) or "").strip()

    with open("seeds/aethryn/splash.txt", encoding="utf-8") as handle:
        splash = handle.read().rstrip("\n")
    emit("\x1b[38;5;214m" + splash + "\x1b[0m\r\n\r\n", 2.0)
    emit("Welcome, Forger. Type HELP to begin.\r\n\r\n", 1.1)

    for cmd, hold in NARRATIVE:
        prompt_and_type(cmd)
        emit(play(cmd) + "\r\n\r\n", hold)

    for _ in range(12):  # the fight: brisk strikes, a long hold on the killing blow
        prompt_and_type("attack wight")
        reply = play("attack wight")
        done = "cold is broken" in reply.lower()
        emit(reply + "\r\n\r\n", 3.2 if done else 0.6)
        if done:
            break

    return events


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    cast_path = args[0] if args else "demo.cast"
    events = build_cast(Session(player_id="forger", location=START_ROOM))
    header = {"version": 2, "width": WIDTH, "height": HEIGHT, "title": "CodeForge: The Relighting"}
    with open(cast_path, "w", encoding="utf-8") as handle:
        handle.write(json.dumps(header) + "\n")
        for event in events:
            handle.write(json.dumps(event) + "\n")
    duration = events[-1][0] if events else 0
    print(
        f"wrote {cast_path}: {len(events)} events, ~{duration}s. Render with agg (see docstring)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
