"""Record the README demo GIF from REAL aethryn gameplay - reproducible, not hand-captured.

The demo is not a mystery artifact: it is generated by driving the actual engine tick through the
Relighting arc and pacing the transcript into an asciinema v2 cast. Combat is deterministic, so the
same script yields the same session every run.

Usage:
    FORGE_SEED=aethryn python scripts/record_demo.py [cast_path]   # writes the .cast
    agg --theme dracula --font-size 15 --speed 1.2 --fps-cap 24 \\
        --last-frame-duration 4 demo.cast docs/demo.gif           # renders the GIF

`agg` (the asciinema gif generator) is the only extra tool needed, and only to render; it is not a
runtime or CI dependency. `make demo-gif` runs both steps.
"""

from __future__ import annotations

import json
import os
import sys
import tempfile

os.environ.setdefault("FORGE_SEED", "aethryn")
# The coda swears an Order (a named-hero action that persists), so point at a throwaway DB -- the
# recorder must never touch real save state, and a fresh file boots with the full current schema.
_demo_db = os.path.join(tempfile.gettempdir(), "codeforge_demo_recorder.db")
if os.path.exists(_demo_db):
    os.remove(_demo_db)
os.environ.setdefault("CODEFORGE_DB", _demo_db)

import forge  # noqa: E402  (import after FORGE_SEED so the world loads the flagship)
from parts.world.session import Session  # noqa: E402
from parts.world.world import START_ROOM  # noqa: E402

WIDTH, HEIGHT = 94, 34
AMBER_PROMPT = "\x1b[1;38;5;214m> \x1b[0m"

# The CRADLE: wake on the shore, see the callings, take one, learn its moves, take the spark, and
# take up the Relighting. (label, seconds to hold the reply on screen)
CRADLE: list[tuple[str, float]] = [
    ("look", 2.1),
    ("jobs", 1.8),
    ("job vanguard", 1.5),
    ("skills", 1.9),
    ("get ember", 1.8),
    ("north", 1.9),
    ("quest accept", 2.1),
]


def build_cast(session: Session) -> list[list[object]]:
    """Drive the game and return asciinema v2 output events with paced, synthetic timestamps.

    A real, reproducible walkthrough of the whole aethryn arc: creation + callings, ability combat,
    leveling, the self-reforging bridge, the lethal boss, and the victory epilogue. Combat is
    deterministic, so every run yields the same session."""
    events: list[list[object]] = []
    clock = 0.0

    def emit(data: str, hold: float) -> None:
        nonlocal clock
        events.append([round(clock, 3), "o", data.replace("\n", "\r\n")])
        clock += hold

    def prompt_and_type(cmd: str) -> None:
        emit(AMBER_PROMPT, 0.15)
        for char in cmd:
            emit(char, 0.04)
        emit("\r\n", 0.3)

    def play(cmd: str) -> str:
        return (forge.handle_command(session, cmd) or "").strip()

    def beat(cmd: str, hold: float) -> str:
        prompt_and_type(cmd)
        reply = play(cmd)
        emit(reply + "\r\n\r\n", hold)
        return reply

    with open("seeds/aethryn/splash.txt", encoding="utf-8") as handle:
        splash = handle.read().rstrip("\n")
    emit("\x1b[38;5;214m" + splash + "\x1b[0m\r\n\r\n", 2.0)
    emit("Welcome, Forger. Type HELP to begin.\r\n\r\n", 1.1)

    # 1. The cradle.
    for cmd, hold in CRADLE:
        beat(cmd, hold)

    # 2. Cross the broken bridge -- it reforges itself as you carry your spark onto it.
    beat("north", 2.2)

    # 3. Into the wilds: strike the reach wolf with a job ability, and grow stronger.
    beat("south", 0.9)
    beat("east", 1.4)
    for i in range(4):  # visible fights: an ability strike, a plain strike, and a level-up lands
        beat("use ember edge on wolf" if i % 2 == 0 else "attack wolf", 1.4)
    while session.level < 5:  # then grind off-screen until strong enough to face the boss
        play("attack wolf")

    # 4. Delve: walk back and down into the Cold Cellar -- entering it advances the quest.
    beat("west", 0.9)
    beat("down", 1.3)
    beat("down", 1.6)

    # 5. The lethal boss: alternate an ability and a strike (checking MP first, so a skill only
    #    fires when it can) until the Relighting is complete; hold long on the victory epilogue.
    for i in range(16):
        can_cast = session.resources["mp"].current >= 3  # Ember Edge costs 3 MP
        cmd = "use ember edge on wight" if (i % 2 == 0 and can_cast) else "attack wight"
        prompt_and_type(cmd)
        reply = play(cmd)
        done = "relighting is complete" in reply.lower()
        emit(reply + "\r\n\r\n", 4.5 if done else 0.7)
        if done:
            break

    # 6. The living game, on the coast: the boss dropped gear + coins. Take up the hammer and
    #    equip it, swear an Order (both bend your stats in a real fight), check the purse, and see
    #    the coast is only the first of three roads -- the Spiral and the Cinderdeep still call.
    session.named = True  # a proven Forger: named heroes may swear an Order (and their deeds save)
    beat("get hammer", 1.6)
    beat("equip hammer", 1.9)
    beat("join warcraft", 2.2)
    beat("wallet", 1.7)
    beat("quest", 3.4)

    return events


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    cast_path = args[0] if args else "demo.cast"
    events = build_cast(Session(player_id="forger", location=START_ROOM))
    header = {"version": 2, "width": WIDTH, "height": HEIGHT, "title": "CodeForge: The Kindlands"}
    with open(cast_path, "w", encoding="utf-8") as handle:
        handle.write(json.dumps(header) + "\n")
        for event in events:
            handle.write(json.dumps(event) + "\n")
    duration = events[-1][0] if events else 0
    print(
        f"wrote {cast_path}: {len(events)} events, ~{duration}s. Render with agg (see docstring)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
