"""CARD: hosted_world -- turn a generated region into a bootable, hostable World Package: the engine
side of North Star #5 (one small hosted world). A generated region becomes a real seed the server
can serve, its identity and spawn validated by the engine's OWN manifest gates.

game_linker (MOD-10.085) writes a region's rooms + quest; a runnable World Package needs one more
thing: a `world.yaml` MANIFEST (world_id, title, start_room, version) -- the typed identity the
server boots and `codeforge seeds` lists. This installs that: it links the region as a seed under
`<root>/content/blueprints/<name>/`, writes the manifest, and validates the identity through the
engine's own `world_manifest.describe_world` gate (fails loud on a bad id/title/start_room). The
declared spawn IS the seed's first room by construction -- the Linker now emits the start FIRST --
which the test proves independently with the engine's `check_world`.

  * `install_world(spec, blueprint_root, *, seed_name=, title=)` -- link + manifest + validate,
    returning
    a HostedWorld verdict: HOSTABLE (links + a valid manifest), UNHOSTABLE (a manifest problem,
    surfaced, never hidden), or REFUSED (the region did not link at all).

The live cloud DEPLOY of a hosted world is a founder-gated action (deployment automation is not the
engine's to trigger); this proves a world is READY to host -- bootable, identified, and (via
game_lifecycle) restorable -- never that it is deployed. Readiness, never certified.

Grammar before worlds: kernel/domains (world-aware), composing game_linker + world_manifest;
kernel/seedlab imports neither. Verdicts, not booleans. Status: PROTOTYPED (see
docs/seed_platform/RECENTERING.md).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from kernel.domains.game_linker import LINKED, GameSpec, link_and_validate
from kernel.world.seed import SEEDS_ROOT

# --- host-readiness verdict words (a distinct vocabulary: "can the server boot this world?") ----
HOSTABLE = "hostable"  # links, the manifest is valid, and the declared spawn is the seed's spawn
UNHOSTABLE = (
    "unhostable"  # links, but the manifest is invalid or the declared spawn is inconsistent
)
REFUSED = "refused"  # the region did not link: there is no world to host

_ID_RE = re.compile(r"[^a-z0-9]+")


class HostedWorldError(Exception):
    """A GameSpec cannot even be named as a world (an empty, unslug-able region). Fails loud."""


@dataclass(frozen=True)
class HostedWorld:
    """The honest verdict on installing a region as a bootable World Package."""

    verdict: str
    seed_name: str = ""
    seed_dir: str = ""
    start_room: str = ""
    files: tuple[str, ...] = ()
    problems: tuple[str, ...] = field(default_factory=tuple)  # why, when not HOSTABLE

    @property
    def ok(self) -> bool:
        return self.verdict == HOSTABLE


def _slug(region: str) -> str:
    """A lowercase-hyphenated world_id from a region name (the manifest's id rule)."""
    slug = _ID_RE.sub("-", region.strip().lower()).strip("-")
    if not slug:
        raise HostedWorldError(f"region {region!r} has no hostable world_id")
    return slug


def _blueprint_root(root: Path) -> Path:
    resolver_root = SEEDS_ROOT.parents[1]
    return SEEDS_ROOT if root == resolver_root else root / SEEDS_ROOT.relative_to(resolver_root)


def install_world(
    spec: GameSpec,
    blueprint_root: Path,
    *,
    seed_name: str = "",
    title: str = "",
) -> HostedWorld:
    """Install a generated region as a bootable World Package under
    `<blueprint_root>/content/blueprints/`
    and validate its identity through the engine's own gate. Links the region (rooms + quest,
    start-first so the seed spawns at the declared start), writes a `world.yaml` manifest, then
    validates it with `describe_world`. HOSTABLE when it holds; REFUSED if it never linked."""
    name = seed_name or _slug(spec.region)
    blueprint_root = Path(blueprint_root)
    seed_dir = _blueprint_root(blueprint_root) / name

    linked, verdict = link_and_validate(spec, seed_dir)
    if verdict.verdict != LINKED:
        return HostedWorld(
            REFUSED, name, str(seed_dir), problems=(f"region did not link: {verdict.verdict}",)
        )

    display = title or name.replace("-", " ").title()
    manifest = (
        f"world_id: {name}\n"
        f"title: {display}\n"
        f"start_room: {spec.start}\n"
        'version: "1"\n'
        f"description: A journey world generated by CodeForge from region {spec.region!r}.\n"
    )
    (seed_dir / "world.yaml").write_text(manifest, encoding="utf-8")

    # Validate the identity through the engine's OWN gate: a bad id/title/start_room fails loud in
    # describe_world. The declared spawn is the seed's first room BY CONSTRUCTION (start-first);
    # the test proves that independently with the engine's check_world.
    from kernel.world.world_manifest import WorldManifestError, describe_world

    files = tuple(sorted([*linked.files, "world.yaml"]))
    try:
        describe_world(name, root=blueprint_root)
    except WorldManifestError as exc:
        return HostedWorld(UNHOSTABLE, name, str(seed_dir), spec.start, files, (str(exc),))
    return HostedWorld(HOSTABLE, name, str(seed_dir), spec.start, files)
