"""CARD: cli_generator -- generate a small, runnable CLI application from a validated ProjectModel,
record it as an artifact (checksums + provenance), and validate it by running it.

Stage 6 of the Seed Platform directive: the first real TARGET GENERATOR, and the payoff of the
recenter -- proof the platform produces working software, not just models of it. Given a
`ProjectModel` (from Stage 4), `generate_cli` emits a small but genuinely runnable Python CLI:

  * a package (`<slug>/__init__.py` + `<slug>/__main__.py`) with an argparse CLI whose subcommands
    come from the model's `actions` (or a default `info` command when none were inferred);
  * a generated test (`tests/test_cli.py`) + a `conftest.py` so it imports cleanly;
  * a `pyproject.toml` (with a console-script entry point) and a `README.md`.

Output is **reproducible** (no timestamps in the emitted code, so the same model yields identical
files and checksums), each file is **checksummed** (sha256), and the artifact carries the model's
**provenance**. `validate_runs` and `validate_tests` prove the target actually RUNS and its tests
PASS -- by executing it through the Stage-5 `tool_runner` (the vertical slice closes on itself).
`rollback` removes a generated tree. No `kernel/world/` coupling. Status: PROTOTYPED (see
docs/seed_platform/RECENTERING.md).
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path

from kernel.seedlab.project_model import ProjectModel, Provenance
from kernel.seedlab.source_connector import LocalSource
from kernel.seedlab.tool_runner import ToolRunResult, run_tool

_SLUG = re.compile(r"[^a-z0-9]+")


class GeneratorError(Exception):
    """The model cannot be turned into a target (e.g. an empty identity). Fails loud."""


@dataclass(frozen=True)
class GeneratedArtifact:
    """The record of a generated target: what was produced, where, its integrity + provenance."""

    name: str  # the pyproject project name (dashed slug)
    package: str  # the importable package name (underscored slug)
    dest: str
    files: list[str]  # generated relpaths, sorted
    checksums: dict[str, str]  # relpath -> sha256
    manifest_hash: str  # sha256 over the sorted (relpath, checksum) pairs -- one id for the whole
    provenance: Provenance
    model_identity: str
    commands: list[str] = field(default_factory=list)


def _package_name(identity: str) -> str:
    slug = _SLUG.sub("_", identity.strip().lower()).strip("_")
    if not slug:
        raise GeneratorError("cannot generate a CLI from a model with an empty identity")
    if slug[0].isdigit():
        slug = f"app_{slug}"
    return slug


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _emit_files(model: ProjectModel, package: str, name: str) -> dict[str, str]:
    """Build the {relpath: content} map for the generated CLI. Pure + deterministic."""
    commands = [c for c in model.actions if _SLUG.sub("_", c.lower()).strip("_")] or ["info"]
    safe_commands = [_SLUG.sub("_", c.lower()).strip("_") for c in commands]
    desc = json.dumps(model.identity)  # safely embed as a string literal
    cmd_list = ", ".join(json.dumps(c) for c in safe_commands)
    first = safe_commands[0]

    main_py = f'''\
"""{model.identity} -- a CLI generated by CodeForge from a project model."""

import argparse

__version__ = "0.1.0"

COMMANDS = [{cmd_list}]


def main(argv=None):
    parser = argparse.ArgumentParser(prog={json.dumps(name)}, description={desc})
    parser.add_argument("--version", action="version", version=__version__)
    sub = parser.add_subparsers(dest="command")
    for _name in COMMANDS:
        sub.add_parser(_name, help=f"the {{_name}} command")
    args = parser.parse_args(argv)
    if args.command:
        print(f"{{args.command}}: ok")
        return 0
    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

    test_py = f"""from {package}.__main__ import main


def test_a_command_runs():
    assert main([{json.dumps(first)}]) == 0


def test_no_command_is_ok():
    assert main([]) == 0
"""

    conftest_py = (
        "import os\nimport sys\n\nsys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))\n"
    )

    pyproject = (
        "[project]\n"
        f'name = "{name}"\n'
        'version = "0.1.0"\n'
        f"description = {desc}\n\n"
        "[project.scripts]\n"
        f'{name} = "{package}.__main__:main"\n'
    )

    readme = (
        f"# {model.identity}\n\n"
        "A small CLI generated by CodeForge from a project model.\n\n"
        f"- source: {model.provenance.source_id} (owner: {model.provenance.owner})\n"
        f"- commands: {', '.join(safe_commands)}\n\n"
        f"Run: `python -m {package} --version`\n"
    )

    return {
        f"{package}/__init__.py": '__version__ = "0.1.0"\n',
        f"{package}/__main__.py": main_py,
        "tests/test_cli.py": test_py,
        "conftest.py": conftest_py,
        "pyproject.toml": pyproject,
        "README.md": readme,
    }


def generate_cli(model: ProjectModel, dest: Path) -> GeneratedArtifact:
    """Generate a runnable CLI from a model into an empty `dest`. Reproducible + checksummed."""
    if not model.identity or not model.identity.strip():
        raise GeneratorError("a project model needs a non-empty identity to generate a CLI")
    dest = Path(dest)
    if dest.exists() and any(dest.iterdir()):
        raise GeneratorError(f"destination {dest} is not empty; refusing to overwrite")
    package = _package_name(model.identity)
    name = package.replace("_", "-")
    contents = _emit_files(model, package, name)

    checksums: dict[str, str] = {}
    for rel, text in contents.items():
        path = dest / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        checksums[rel] = _sha256(text)

    manifest_hash = _sha256("\n".join(f"{r}:{checksums[r]}" for r in sorted(checksums)))
    commands = [c for c in model.actions if c.strip()] or ["info"]
    return GeneratedArtifact(
        name=name,
        package=package,
        dest=str(dest),
        files=sorted(contents),
        checksums=checksums,
        manifest_hash=manifest_hash,
        provenance=model.provenance,
        model_identity=model.identity,
        commands=[_SLUG.sub("_", c.lower()).strip("_") for c in commands],
    )


def _target_source(artifact: GeneratedArtifact) -> LocalSource:
    return LocalSource(Path(artifact.dest), artifact.provenance)


def validate_runs(artifact: GeneratedArtifact, *, seed_id: str = "_generate") -> ToolRunResult:
    """Prove the generated target RUNS: `python -m <package> --version` in its own dir (exit 0)."""
    return run_tool(
        _target_source(artifact),
        "run",
        seed_id=seed_id,
        kind="build",
        allowlist={"run": [sys.executable, "-m", artifact.package, "--version"]},
    )


def validate_tests(artifact: GeneratedArtifact, *, seed_id: str = "_generate") -> ToolRunResult:
    """Prove the generated target's TESTS PASS: run its pytest suite through the Stage-5 runner."""
    return run_tool(
        _target_source(artifact),
        "pytest",
        seed_id=seed_id,
        kind="test",
        allowlist={
            "pytest": [sys.executable, "-m", "pytest", "tests/", "-q", "-p", "no:cacheprovider"]
        },
    )


def rollback(artifact: GeneratedArtifact) -> None:
    """Remove a generated tree (cleanup/rollback). Idempotent."""
    shutil.rmtree(artifact.dest, ignore_errors=True)


def render_artifact(artifact: GeneratedArtifact) -> str:
    """A human summary of a generated artifact (files, integrity, provenance)."""
    return "\n".join(
        [
            f"GENERATED TARGET: {artifact.name}  (a CLI from model '{artifact.model_identity}')",
            f"  package:      {artifact.package}",
            f"  commands:     {', '.join(artifact.commands)}",
            f"  files ({len(artifact.files)}): {', '.join(artifact.files)}",
            f"  manifest sha: {artifact.manifest_hash[:16]}...",
            f"  provenance:   {artifact.provenance.source_id} "  # noqa: ISC004
            f"(owner: {artifact.provenance.owner}, {artifact.provenance.visibility})",
            f"  path:         {artifact.dest}",
        ]
    )
